spring:
  application:
    name: payer-daily-default

server:
  port: 8442
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

